### ISSUE TITLE
Fix or remove broken filesystem migration

### ISSUE THREAD

**Issue by matjaeck** [matjaeck/OpenRAUserAccounts#20]
The only thing it should do is to make the directory for the badges. The issue is that it requires an own constructor which seems to overwrite the parent's class constructor which breaks the other functions used in the migration file. Calling the parent constructor within the child's did not help, might have done it wrong. It might be possible to include all objects of the parent constructor in the child constructor so that it can overwrite it without breaking anything.

Low priority though and probably wasted time as the directory can easily be created manually. Might be better to just delete it.

**Comment by pchote** [comment]
:+1: for deleting it.  I would also be happy with removing the custom ACP logic for selecting a badge image from the directory, and have a simple textfield instead (which would allow us to link to images hosted on GitHub or similar if we wanted).

**Comment by matjaeck** [comment]
Deleted.
