### ISSUE TITLE
Add another UCP tab for non-default badges

### ISSUE THREAD

**Issue by matjaeck** [matjaeck/OpenRAUserAccounts#29]
Like the 'Default badges' tab but will list "special" badges the user earned. This is consistent with the current system which allows the user to select badges from default/special badges tab and then manage their order in the profile badges tab. Parts of the 'default_badges' code can be reused for this.

**Comment by pchote** [comment]
I have proposed an implementation for this in #19.

**Comment by matjaeck** [comment]
Implemented as suggested. Renamed `Default badges` to `Select badges` and `Profile badges` to `Order badges`.
