### ISSUE TITLE
Specify and check maximum badge label length

### ISSUE THREAD

**Issue by matjaeck** [matjaeck/OpenRAUserAccounts#8]
Currently uses a VCHAR:255 but this will need to be adjusted to the length that fits the game UI.

**Comment by lawando** [comment]
This is now `badge_title` in table `openra_badges`.

**Comment by lawando** [comment]
Length should be checked on 'save' before the insert/update query runs, https://github.com/lawando/OpenRAUserAccounts/blob/master/acp/badges_module.php#L79.

**Comment by matjaeck** [comment]
All badge data  will be inserted by the board admin which allows to relinquish input validation. This is in the foreseeable future not within the scope of development so closing for now.
